In [2]:
import numpy as np

In [9]:
# Завдання 1
# Створіть одновимірний масив (вектор) зі значеннями натуральних чисел, починаючи з 1, та виведіть його значення.
vector = np.arange(1, 11)
print(vector)

[ 1  2  3  4  5  6  7  8  9 10]


In [12]:
# Завдання 2
# Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його косинусами кожного натурального числа, починаючи з 1, та виведіть його значення.
matrix = np.cos(np.arange(1, 10).reshape(3, 3))
print(matrix)

[[ 0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029]
 [ 0.75390225 -0.14550003 -0.91113026]]


In [6]:
# Завдання 3
# Створіть масив розміром 3x3, заповніть його випадковими цілими числами від -5 до 5 та виведіть непарні числа.
arrays = np.array(np.random.randint(-5, 6, size=(3, 3)))
print(arrays)
unpaired_numbers = arrays[arrays % 2 != 0]
print("Непарні числа виглядять так:",unpaired_numbers)

[[-5 -5  0]
 [-3  5 -4]
 [ 4  4  0]]
Непарні числа виглядять так: [-5 -5 -3  5]


In [7]:
# Завдання 4
# Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від -0.7 до 0.7 та виведіть його значення.
arrays = np.array(np.random.uniform(-0.7, 0.7, size=(4, 4)))
print(arrays)

[[-0.33643375 -0.52406802 -0.16792328  0.09176737]
 [-0.33297333 -0.46994682  0.03886378 -0.04361633]
 [ 0.31915981 -0.45583836  0.36243828  0.62836042]
 [ 0.42782981 -0.30033038 -0.45138661 -0.24092739]]


In [8]:
# Завдання 5
#Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 10 до 20 та виконайте на них поелементні операції додавання, віднімання та множення.
array1 = np.array(np.random.randint(10, 21, size=5))
array2 = np.array(np.random.randint(10, 21, size=5))
print(array1 + array2)
print(array1 - array2)
print(array1 * array2)

[22 26 31 32 32]
[ 0 -6  3 -8  0]
[121 160 238 240 256]


In [21]:
# Завдання 6
# Створіть дві матриці 4x4, заповніть їх довільними цілими числами від 1 до 10 та знайдіть їх добуток
matrix1 = np.random.randint(1, 11, size=(4,4))
matrix2 = np.random.randint(1, 11, size=(4,4))
result = np.dot(matrix1, matrix2)
print(result)

[[126 155 153  89]
 [118 136 128  78]
 [131 139 126 109]
 [210 239 213 148]]


In [22]:
# Завдання 7
# Створіть дві матриці розміром 2x3 та 3x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 5 та перемножте їх між собою.
matrix1 = np.random.randint(1, 6, size=(2, 3))
matrix2 = np.random.randint(1, 6, size=(3, 3))
result = np.dot(matrix1, matrix2)
print(result)

[[43 29 36]
 [32 13 28]]


In [25]:
# Завдання 8
# Створіть матрицю розміром 2x2, заповніть її випадковими цілими числами в діапазоні від 1 до 12 та знайдіть її обернену матрицю.
matrix = np.random.randint(1, 13, size=(2, 2))
print("Матриця до обернення:", "\n", matrix)
inverse_matrix = np.linalg.inv(matrix)
print("Матриця після обернення:", "\n", inverse_matrix)

Матриця до обернення: 
 [[12  9]
 [ 9  1]]
Матриця після обернення: 
 [[-0.01449275  0.13043478]
 [ 0.13043478 -0.17391304]]


In [29]:
# Завдання 9
# Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її
matrix = np.random.uniform(0, 1, size=(3, 3))
print("Матриця до транспонування","\n", matrix)
print("Матриця після транспонування","\n", matrix.T)

Матриця до транспонування 
 [[0.64615937 0.2403161  0.1175385 ]
 [0.73813842 0.48391117 0.30830301]
 [0.30559824 0.10524921 0.27731282]]
Матриця після транспонування 
 [[0.64615937 0.73813842 0.30559824]
 [0.2403161  0.48391117 0.10524921]
 [0.1175385  0.30830301 0.27731282]]


In [36]:
# Завдання 10
# Створіть матрицю розміром 3x4 та вектор розміром 4x1, заповніть матрицю випадковими цілими числами в діапазоні від 1 до 10, а вектор - випадковими дійсними числами від 0 до 1, і знайдіть добуток матриці на вектор.
matrix = np.random.randint(1, 11, size=(3, 4))
vector = np.random.uniform(0, 1, size=(4, 1))
result = np.dot(matrix, vector)
print(result)


[[16.81292858]
 [20.57625931]
 [10.48822745]]


In [37]:
# Завдання 11
# Створіть матрицю розміром 2x3 та вектор розміром 3x1, заповніть матрицю випадковими дійсними числами від 0 до 1, а вектор - випадковими цілими числами в діапазоні від 1 до 10, і знайдіть добуток матриці на вектор.
matrix = np.random.uniform(0, 1, size=(2, 3))
vector = np.random.randint(1, 11, size=(3,1))
result = np.dot(matrix, vector)
print(result)

[[16.24570338]
 [ 7.00749237]]


In [41]:
# Завдання 12
# Створіть дві матриці розміром 3x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 5 та знайдіть суму всіх елементів першої матриці.
matrix1 = np.random.randint(1, 6, (3, 3))
matrix2 = np.random.randint(1, 6, (3, 3))
print("Перша матриця:", "\n", matrix1)
print("Друга матриця:", "\n", matrix2)
print("Сума всіх елементів першої матриці:", np.sum(matrix1))

Перша матриця: 
 [[3 1 5]
 [3 3 1]
 [1 3 1]]
Друга матриця: 
 [[5 2 5]
 [4 4 5]
 [4 1 1]]
Сума всіх елементів першої матриці: 21


In [43]:
# Завдання 13
# Створіть дві матриці розміром 4x4, заповніть їх випадковими дійсними числами в діапазоні від -2 до 2 та знайдіть добуток їх елементів.
matrix1 = np.random.uniform(-2, 2, size=(4, 4))
matrix2 = np.random.uniform(-2, 2, size=(4, 4))
print("Перша матриця:", "\n", matrix1)
print("Друга матриця:", "\n", matrix2)
print("Добуток елементів матриць:","\n", matrix1 * matrix2)

Перша матриця: 
 [[ 0.89685786  0.60850902 -1.76416921  1.96132741]
 [-1.20769001 -0.35580808  0.11706873 -1.1424536 ]
 [-0.76831123  1.93674885 -1.9212246   1.49531511]
 [ 1.14790072  0.45709794 -1.51746312 -0.65896878]]
Друга матриця: 
 [[-0.13728388  1.97018567 -0.20033705  1.2250373 ]
 [ 1.89158942 -0.49071533 -1.31021011  1.53014592]
 [ 0.95274127 -1.97338152  1.53203295  0.97893972]
 [ 1.48016245  1.32759264 -1.2899835  -0.64816155]]
Добуток елементів матриць: 
 [[-0.12312413  1.19887575  0.35342845  2.40269924]
 [-2.28445365  0.17460048 -0.15338463 -1.74812071]
 [-0.73200182 -3.8219444  -2.9433794   1.46382336]
 [ 1.69907954  0.60683986  1.95750239  0.42711822]]


In [44]:
# Завдання 14
# Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від -10 до 10 та знайдіть найменший елемент матриці.
matrix = np.random.uniform(-10, 10, size=(3, 3))
print(matrix)
min_element = np.min(matrix)
print("Найменший елемент матриці:", min_element)

[[-2.04403591 -4.33975793  8.57490037]
 [-5.23409914 -2.22706288 -1.31206928]
 [ 9.43394116  4.2897881  -0.68628649]]
Найменший елемент матриці: -5.23409913799902


In [46]:
# Завдання 15
# Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного стовпця матриці.
matrix = np.random.uniform(0,1, size=(3,3))
print(matrix)
column_sums = np.sum(matrix, axis=0)
print("Вектор-стовпчик (сума елементів кожного стовпця):", column_sums)

[[0.10504399 0.06563349 0.87928394]
 [0.46078325 0.70958027 0.99747015]
 [0.27679102 0.86405289 0.36276746]]
Вектор-стовпчик (сума елементів кожного стовпця): [0.84261826 1.63926665 2.23952154]
